### ISSUE TITLE
Can't find routes

### ISSUE THREAD

**Issue by darkwebdev** [marko-js/markojs-website#16]
My actions:
1. git clone git@github.com:marko-js/markojs-website.git
2. cd markojs-website
3. npm install
4. npm start

Output on the last action:
```
> markojs-website@1.0.0 start /Users/tmanyanov/projects/markojs-website
> marko-starter server

[browser-refresh] Watching: /Users/tmanyanov/projects/markojs-website
[browser-refresh] Watching: /Users/tmanyanov/projects/markojs-website/node_modules/marko/docs
[browser-refresh] Ignore rule: static
[browser-refresh] Ignore rule: node_modules
[browser-refresh] Ignore rule: *.marko.js
[browser-refresh] Ignore rule: .cache
[browser-refresh] Ignore rule: .nyc_output
[browser-refresh] Ignore rule: npm-debug.log
[browser-refresh] Ignore rule: .DS_Store
[browser-refresh] Ignore rule: /dist
[browser-refresh] Ignore rule: components-generated/*
[browser-refresh] Ignore rule: !components-generated/.gitkeep
[browser-refresh] App started (pid: 15388)
[marko-starter plugins] Installed plugin: lasso
[marko-starter plugins] Installed plugin: generic-http-server
[marko-starter init] Error starting server. Error: A route must contain a `route.js` file that exports a template or handler, or the route must contain an `index.marko` file.
At: /Users/tmanyanov/projects/markojs-website
    at Object.onRoute (/Users/tmanyanov/projects/markojs-website/node_modules/marko-starter/src/util/loadFilesystemRoutes.js:32:17)
    at buildRoute (/Users/tmanyanov/projects/markojs-website/node_modules/routes-table/index.js:122:25)
    at addRoutes (/Users/tmanyanov/projects/markojs-website/node_modules/routes-table/index.js:73:42)
    at build (/Users/tmanyanov/projects/markojs-website/node_modules/routes-table/index.js:46:9)
    at Promise (/Users/tmanyanov/projects/markojs-website/node_modules/routes-table/index.js:25:9)
    at Object.exports.build (/Users/tmanyanov/projects/markojs-website/node_modules/routes-table/index.js:24:19)
    at module.exports (/Users/tmanyanov/projects/markojs-website/node_modules/marko-starter/src/util/loadFilesystemRoutes.js:12:22)
    at _triggerProjectHook.then (/Users/tmanyanov/projects/markojs-website/node_modules/marko-starter/src/util/createProject.js:86:14)
    at process._tickCallback (internal/process/next_tick.js:109:7)
App stopped unexpectedly
[browser-refresh] Waited 3000ms without receiving "online" from child process. Page refresh triggered over WebSockets connection.
[browser-refresh] Triggering refresh of client pages...
[browser-refresh] Refresh triggered
```

**Comment by austinkelleher** [comment]
Thanks for opening this issue. This looks like an issue related to one of our dependencies. Investigating.

**Comment by austinkelleher** [comment]
Fixed in https://github.com/marko-js/marko-starter/pull/10 and https://github.com/mlrawlings/routes-table/pull/4
